version: "3"
services:
  sonarqube:
    image: sonarqube:latest
    restart: always
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_WEB_PORT: 9999
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - ./sonarqube_data/conf:/opt/sonarqube/conf \
      - ./sonarqube_data/logs:/opt/sonarqube/data \
      - ./sonarqube_data/data:/opt/sonarqube/logs \
      - ./sonarqube_data/extensions:/opt/sonarqube/extensions \
    ports:
      - "9999:9999"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data